### ISSUE TITLE
Quill live demo is not working

### ISSUE THREAD

**Issue by seleckis** [yjs/yjs-demos#57]
Quill live demo is not working, showing "Application error": https://demos.yjs.dev/quill/quill.html

As well as demo is not working locally.

Steps to reproduce:
1. Clone yjs-demos repository.
2. Navigate to yjs-demos/quill
3. install dependencies `npm i`
4. Run with `npm start`

Expected result: Some demo in a browser

Actual result:
```
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ webpack-dev-server --open-page quill.html
ℹ ｢wds｣: Project is running at http://localhost:8081/
ℹ ｢wds｣: webpack output is served from /dist/
ℹ ｢wds｣: Content not from webpack is served from /Users/seleckis/Sites/yjs-demos/quill
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/seleckis/Sites/yjs-demos/quill/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/seleckis/Sites/yjs-demos/quill/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/seleckis/Sites/yjs-demos/quill/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/seleckis/Sites/yjs-demos/quill/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/seleckis/Sites/yjs-demos/quill/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/seleckis/Sites/yjs-demos/quill/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/seleckis/Sites/yjs-demos/quill/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/seleckis/Sites/yjs-demos/quill/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
error Command failed with exit code 1.
```

**Comment by DHclly** [comment]
this repo is so bad,nothing can run success.

**Comment by dmonad** [comment]
This issue is pretty old and is already fixed . I confirmed that the repo runs in node v18 now.

@DHclly your comment is not very productive. If there is a concrete issue, please open a ticket with a detailed description.
